#externalIPs:
imagePullSecrets: []
resources: {}
  # Example
  #    limits:
  #      cpu: 3800m
  #      memory: 8000Mi
nodeSelector: {}
affinity: {}
nodeName:
monitoring:
  logs:
    # TODO: optional https://github.com/timberio/vector side car
  metrics:
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
    prometheusOperator:
      enabled: true
      releaseName: prometheus-stack # SHOULD BE THE PROM OPERATOR CLUSTER RELEASE CHART NAME
    stackdriverProjectId: ""
    prometheusPort: 9090


# for example
# extraEnvs:
#  - name: MY_PLUGIN_IS_A_SINGULARITY_THAT_WILL_TAKE_OVER_THE_WORLD
#    value: "666"
#
extraEnvs: []

console:
  port: 7351
  grpc: 7348
  nodePort: 30021
  username: "admin"
  password: "password"

runtime:
  httpKey: "defaultkey"

socket:
  port: 7350
  serverKey: "defaultkey"
  type: "LoadBalancer" #"NodePort"
  nodePort: 30020
  outgoingQueueSize: 16

matchmaker:
  intervalSec: 15
  maxIntervals: 2
  maxTickets: 3

grpc:
  port: 7349

session:
  encryptionKey: "defaultencryptionkey"
  tokenExpirySec: 6000

image:
  repository: "revelation.space/nakama-urtur"
  tag: "v0.0.1t"
  pullPolicy: IfNotPresent

database:
  deploy: false
  size: 1000Mi
  type: cockroachdb
  url: "cockroachdb-public.cockroachdb"
  port: 26257

# cockroachdb:
#   image:
#     repository: cockroachdb/cockroach
#     tag: v20.2.4
#     pullPolicy: IfNotPresent

# Using postgres?
# postgres:
#  image:
#    repository: postgres
#    tag: v12.2-alpine
#    pullPolicy: IfNotPresent


# Want to use k8s api ?
clusterRole:
  enabled: false

extraConfigMaps:
